steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=ci-pipeline-sa.json.enc
  - --plaintext-file=ci-pipeline-sa.json
  - --location=global
  - --keyring=ci-pipeline-keyring
  - --key=ci-pipeline-key

- name: 'gcr.io/cloud-builders/docker'
  id: Build Application Image
  args: [
   'build',
   '--build-arg', 'push_test_results=true',
   '-t', 'gcr.io/cookbook-1180/push-artifacts',
   '-f', './Dockerfile',
   '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: Push Image
  args: [
   'push',
   'gcr.io/cookbook-1180/push-artifacts'
  ]